# File: main.py
# Author: William Jahner

from sentence_transformers import SentenceTransformer, util
import torch
from .services.ai_service import AIService
from .services.kb_loader import load_knowledge_base
from .services.list_service import get_milestone_list

######################################################################
# Class: NewParentAIAssistantApp
# Description: This class is a testable wrapper around the New Parent
#              AI Assistant.
######################################################################
class NewParentAIAssistantApp:

    ######################################################################
    # Module: __init__
    # Description: Constructor for NewParentAIAssistantApp
    # Input:
    #   - self: instance of the class itself
    #   - knowledge_base: the knowledge base for the NLP model
    # Returns: N/A
    ######################################################################
    def __init__(self, knowledge_base):
        # Store the raw knowledge base as label/text tuples
        self.knowledge_base = knowledge_base

        # Create the AI service
        self.ai = AIService(knowledge_base)

        # Pre-compute labeled texts
        self.texts = [f"{label}: {text}" for label, text in knowledge_base]

        # Pre-compute embeddings
        self.embeddings = self.ai.embedder.encode(self.texts, convert_to_tensor=True)

    ######################################################################
    # Module: find_best_entries
    # Description: Helper function that returns the top_k most relevant
    #              knowledge base entries.
    # Input:
    #   - self: instance of the class
    #   - question: the question or request from the user input
    #   - top_k: the number of top relevant entries to return
    # Returns: a list of the top_k most relevant knowledge base entries
    ######################################################################
    def find_best_entries(self, question, top_k=3):
        q_embed = self.ai.embedder.encode(question, convert_to_tensor=True)
        scores = util.pytorch_cos_sim(q_embed, self.embeddings)[0]
        top_results = torch.topk(scores, k=top_k)
        return [self.texts[i] for i in top_results.indices]

    ######################################################################
    # Module: answer_question
    # Description: Helper function that returns the QA model's answer
    #              using best matching knowledge base entries.
    # Input:
    #   - self: instance of the class
    #   - question: the question or request from the user input
    # Returns: the answer generated by the QA model
    ######################################################################
    def answer_question(self, question):
        contexts = self.find_best_entries(question)
        context_str = " ".join(contexts)
        result = self.ai.qa_pipeline(question=question, context=context_str)
        return result["answer"]

######################################################################
# Module: print_intro_message
# Description: Prints the introductory message for a user starting up
#              the application
# Input: N/A
# Returns: N/A
######################################################################
def print_intro_message():
    print("\n\033[36mWelcome to the New Parent AI Assistant!\033[0m")
    print("\033[36mThis application is designed to help answer questions for new parents.\033[0m")
    print("\033[36mThis is the initial version of the application, so it only contains information " + \
          "about developmental milestones, feeding, and sleep for babies in their first year.\033[0m")
    print("\033[36mFuture releases of this application will include more categories of baby care.\033[0m")
    print("\033[36mIf you wish to end the program at any time, enter 'exit', 'end', or 'quit'\n\n\033[0m")

######################################################################
# Module: main
# Description: The application's main function
# Input: N/A
# Returns: N/A
######################################################################
def main():
    # Load the knowledge base
    knowledge_base = load_knowledge_base()

    # Create the new parent AI assistant application
    app = NewParentAIAssistantApp(knowledge_base)

    # Print the introductory message
    print_intro_message()

    # Create a list of keywords for listing services
    # Note that for now this is only related to milestones, but in the future
    # it could be expanded to other categories
    list_keywords = ["milestone", "milestones", "developmental milestones"]

    # Main loop
    while True:

        # Prompt the user for input
        user_input = input("\033[36mWhat would you like to know?\n\033[0m").strip().lower()

        # Check for exit conditions
        if user_input in ("exit", "end", "quit"):
            print("\033[36mClosing the New Parent AI Assistant...\033[0m")
            break

        # If keywords are detected, route the user input to the listing service.
        # Otherwise, route the user input to the AI (NLP) question answering service.
        if any(word in user_input for word in list_keywords):
            # Route to the listing service for milestones
            milestone_list = get_milestone_list(knowledge_base, user_input)
            print(f"{milestone_list}\n")
        else:
            # Route to the AI (NLP) question answering service
            response = app.answer_question(user_input)
            print(f"NLP RESPONSE: {response}\n")

#############################################
### Entry point of the application (main) ###
#############################################
if __name__ == "__main__":
    main()
