# File: main.py
# Author: William Jahner

from sentence_transformers import SentenceTransformer, util
import torch
from services.ai_service import AIService
from services.kb_loader import load_knowledge_base

######################################################################
# Class: NewParentAIAssistantApp
# Description: This class is a testable wrapper around the New Parent
#              AI Assistant.
######################################################################
class NewParentAIAssistantApp:

    ######################################################################
    # Module: __init__
    # Description: Constructor for NewParentAIAssistantApp
    # Input:
    #   - self: instance of the class itself
    #   - knowledge_base: the knowledge base for the NLP model
    # Returns: N/A
    ######################################################################
    def __init__(self, knowledge_base):
        # Store the raw knowledge base as label/text tuples
        self.knowledge_base = knowledge_base

        # Create the AI service
        self.ai = AIService(knowledge_base)

        # Pre-compute labeled texts
        self.texts = [f"{label}: {text}" for label, text in knowledge_base]

        # Pre-compute embeddings
        self.embeddings = self.ai.embedder.encode(self.texts, convert_to_tensor=True)

    ######################################################################
    # Module: find_best_entries
    # Description: Helper function that returns the top_k most relevant
    #              knowledge base entries.
    # Input:
    #   - self: instance of the class
    #   - question: the question or request from the user input
    #   - top_k: the number of top relevant entries to return
    # Returns: a list of the top_k most relevant knowledge base entries
    ######################################################################
    def find_best_entries(self, question, top_k=3):
        q_embed = self.ai.embedder.encode(question, convert_to_tensor=True)
        scores = util.pytorch_cos_sim(q_embed, self.embeddings)[0]
        top_results = torch.topk(scores, k=top_k)
        return [self.texts[i] for i in top_results.indices]

    ######################################################################
    # Module: answer_question
    # Description: Helper function that returns the QA model's answer
    #              using best matching knowledge base entries.
    # Input:
    #   - self: instance of the class
    #   - question: the question or request from the user input
    # Returns: the answer generated by the QA model
    ######################################################################
    def answer_question(self, question):
        contexts = self.find_best_entries(question)
        context_str = " ".join(contexts)
        result = self.ai.qa_model(question=question, context=context_str)
        return result["answer"]

######################################################################
# Module: print_intro_message
# Description: Prints the introductory message for a user starting up
#              the application
# Input: N/A
# Returns: N/A
######################################################################
def print_intro_message():
    print("\nWelcome to the New Parent AI Assistant!")
    print("If you wish to end the program at any time, enter 'exit', 'end', or 'quit'\n\n")

######################################################################
# Module: main
# Description: The application's main function
# Input: N/A
# Returns: N/A
######################################################################
def main():
    # Load the knowledge base
    knowledge_base = load_knowledge_base()

    # Create the new parent AI assistant application
    app = NewParentAIAssistantApp(knowledge_base)

    # Print the introductory message
    print_intro_message()

    # Main loop
    while True:

        # Prompt the user for input
        user_input = input("What would you like to know?\n").strip().lower()

        # Check for exit conditions
        if user_input in ("exit", "end", "quit"):
            print("Closing the New Parent AI Assistant...")
            break

        # Get the AI response
        response = app.answer_question(user_input)
        print(f"NLP RESPONSE: {response}\n")

#############################################
### Entry point of the application (main) ###
#############################################
if __name__ == "__main__":
    main()
